import React from 'react';

const AudioSection = () => {


  return (
    <div className="px-6 flex flex-col justify-center items-center bg-gradient-to-r from-teal-100 to-orange-100 rounded-lg shadow max-w-xl mx-auto mt-10">
      <h1 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4 text-center">
        Text to Audio Generator
      </h1>

      <p className="text-lg md:text-xl text-gray-700 mb-6 text-center">
        This is a sample audio generated by our system. Experience fast and accurate text-to-speech conversion.
      </p>

      <audio controls className="w-64 md:w-80 mb-4">
        <source src="/sample_audio_1.mp3" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>

      <a
        href="/sample_audio_1.mp3"
        download
        className="bg-blue-500 text-white px-6 py-2 rounded shadow hover:bg-blue-600 transition"
      >
        Download Audio
      </a>

      <p className=' mt-2 text-neutral-600'>Generated Audio from Audiofy</p>
    </div>
  );
};

export default AudioSection;